# Generated by Django 4.2.1 on 2023-05-04 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 4, 22, 13, 16, 64516)),
            preserve_default=False,
        ),
    ]
